language: node_js
node_js:
- node
- '4'
sudo: false
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null
  2>&1
deploy:
  provider: npm
  api_key:
    secure: XL1yVprbys0m9W2y7re5sjfVkIXmHhJ+i7px9u9cFzBjIlFH2CvutF4u7bG13PDamAeyqzXoUegolbEGU2mopYumOt4SwcOE/hBC3qTYWtuebmZlnL+/kEypjXRXSHdqPuldXdbRMHu2iHe6236yTR7c8uWvQidHY2NeeP80e1aUPfyWVCJIv9E30mMhn4z0nAJxN+S3PCOE6SQU1XpwnXWUHapCcKx/AlDajzY+uJQh4fmY1l5XMFRHE0grpoNTqI2WpXCMdI8Bigy0KpfL7u602EXRjLnhDOmhGorhEirFjE2da0XP2w9z7AR5B7i5gBRV9AK6yJ+PGl7VJ3xxrfeFOeLx4Z7llX61kHkAqpdz47flHLtIka+h5tra6IzG+u3Xs1j4AQPCm24fTUy15y4ru/9qhAtwktk3OAN0WUX5M077EelR07oEjzbfCbFhl62rhpivgqcTEHMroD2wJ9gu9BlGiJS3gkkTnm0xhFti5BYrdpNOOdEIxIWt5/syJl4Nycj9uL2MQQBhziP8oYPVo68A9k0BnY1/rO05xEUv4z7mQxh7RxwK+FDhKHjhy/wVBVYUKp3qcAenXBBS8LXXXNSsBan4DiurrAUDXd6w6tVIgaCj4kenGHfAtUomNNbU2aeYAkMqk7Xowo8dUa1hdCm5EfeZzL6frRcl81A=
  on:
    tags: true
    repo: eiriksm/node-lmtool
